AllCops:
  Exclude:
    - vendor/**/*
    - bin/**/*
    - gemfiles/**/*
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

inherit_from: .rubocop_todo.yml
